FROM fiware/cygnus-ngsi:1.9.0

ADD files/agent.conf /opt/fiware-cygnus//docker/cygnus-ngsi/agent.conf
ADD files/agent.conf /opt/apache-flume/conf/agent.conf
ADD files/grouping_rules.conf /opt/apache-flume/conf/grouping_rules.conf

