version: '2'

networks:
  fiware:
    external: true

services:
  mongodb:
    image: mongo:3.4
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command: --smallfiles
    networks:
      - fiware

  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links:
      - mongodb
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongodb
    networks:
      - fiware

  postgres:
    restart: always
    image: postgres:9.5
    container_name: postgres
    volumes:
      - "./data/postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=teste
      - POSTGRES_DB=newdb
      - POSTGRES_PASSWORD=123456789
    networks:
      - fiware

  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: cygnus
    volumes:
      - "./config/cygnus/cygnus.conf:/opt/apache-flume/conf/agent.conf:rw"
    links:
      - orion
      - postgres
    expose:
      - "5050"
      - "8081"
    ports:
      - "5050:5050"
      - "8081:8081"
    environment:
      - CYGNUS_POSTGRES_USER=teste
      - CYGNUS_POSTGRES_DB=newdb
      - CYGNUS_POSTGRES_PASSWORD=123456789
    networks:
      - fiware

