version: "2"
networks:
  fiware:
    driver: bridge
services:
# Base de datos Orion
  mongo:
    image: mongo:3.4
    hostname: mongo
    container_name: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:      
      - "./data/db/mongodb:/data:rw"
    command: --nojournal
    networks:
      - fiware
# GE encargado de la publicación y suscripción
  orion:
    image: fiware/orion:1.14.0
    hostname: orion
    container_name: orion
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongo
    networks:
      - fiware
# GE encargada de la persistencia de datos
  cygnus:
    build: cygnus
    hostname: cygnus
    container_name: cygnus
    expose:
      - "5050"
      - "5080"
    ports:
      - "5050:5050"
      - "5080:5080"
    environment:
      - CYGNUS_MYSQL_HOST=mysql-idm-cygnus
      - CYGNUS_MYSQL_PORT=3306
      - CYGNUS_MYSQL_USER=root
      - CYGNUS_MYSQL_PASS=fiware
      - CYGNUS_LOG_LEVEL=INFO
    networks:
      - fiware
# base de datos para los historicos y la interfaz
  mysql-idm-cygnus:
    image: mysql:5.7.20
    hostname: mysql-idm-cygnus
    container_name: mysql-idm-cygnus
    expose:
      - "3377"
    ports:
      - "3377:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=fiware
    volumes:
      - "./data/db/mysql:/var/lib/mysql:rw"
    networks:
      - fiware
# habiitador de seguridad
  authzforce:
    image: fiware/authzforce-ce-server:release-5.4.1
    hostname: authzforce
    container_name: authzforce
    expose:
      - "8080" 
    ports: 
      - "8080:8080"
    networks:
      - fiware
# interfaz de configuración y seguridad
  fiware-idm:
    build: fiware-idm
    hostname: fiware-idm
    container_name: fiware-idm
    expose:
      - "3000"
      - "443"
    ports:
      - "3000:3000"
      - "443:443"
    environment:
      - DATABASE_HOST=mysql-idm-cygnus
    networks:
      - fiware
  fiware-pep:
    build: fiware-pep
    hostname: fiware-pep
    container_name: fiware-pep
    expose:
      - "8585"
    ports:
      - "8585:80"
    networks:
      - fiware