version: "2"

networks:
  fiware:
    driver: bridge

services:
  mongodb:
    image: mongo:3.4.7
    hostname: mongodb
    container_name: mongodb
    expose:
      - "27017"
    ports:
      - "27018:27017"
    command: --smallfiles
    networks:
      - fiware

  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links: 
      - mongodb
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongodb
    networks:
      - fiware

  keyrock:
    image: fiware/idm:latest
    hostname: keyrock
    container_name: keyrock
    expose:  
        - "5000"
        - "8000"
    ports:
        - "5000:5000"
        - "8000:8000"
    networks:
        - fiware
         
  pepproxy:
    image: ging/fiware-pep-proxy
    hostname: pepproxy
    container_name: pepproxy
    volumes:
        - "./config/pepproxy/config.js:/opt/fiware-pep-proxy/config.js:rw"
    expose:
        - "80"
    ports:
        - "80:80"
    links:
        - orion
        - keyrock 
    networks:
        - fiware

  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: cygnus
    volumes:
      - "./config/cygnus/agent.conf:/opt/apache-flume/conf/agent.conf:rw"
      - "./config/cygnus/grouping_rules.conf:/opt/apache-flume/conf/grouping_rules.conf:rw"
    links:
      - postgres-cygnus
      - mysql-cygnus
      - mongodb-cygnus
    expose:
      - "5050"
      - "8081"
    ports:
      - "5050:5050"
      - "8081:8081"
    environment:
      - CYGNUS_POSTGRES_USER=postgres
      - CYGNUS_POSTGRES_DB=fiware
      - CYGNUS_POSTGRES_PASSWORD=fiware
      - CYGNUS_MYSQL_HOST=mysql-cygnus
      - CYGNUS_MYSQL_PORT=3306
      - CYGNUS_MYSQL_USER=root
      - CYGNUS_MYSQL_PASS=fiware
      - CYGNUS_LOG_LEVEL=INFO
      - CYGNUS_MONGO_HOSTS=mongodb-cygnus:27017
      - CYGNUS_MONGO_USER=fiware
      - CYGNUS_MONGO_PASS=fiware
    networks:
      - fiware

  postgres-cygnus:
    restart: always
    image: postgres:9.5
    hostname: postgres-cygnus
    container_name: postgres-cygnus
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fiware
      - POSTGRES_PASSWORD=fiware
    volumes:
      - "./data/db/postgres:/var/lib/postgresql/data:rw"
    networks:
      - fiware

  mysql-cygnus:
    image: mysql
    hostname: mysql-cygnus
    container_name: mysql-cygnus 
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=fiware
    volumes:
      - "./data/db/mysql:/var/lib/mysql:rw"
    networks:
      - fiware

  mongodb-cygnus:
    image: mongo:3.4.7
    hostname: mongodb-cygnus
    container_name: mongodb-cygnus
    expose: 
      - "27017"
    ports:
      - "27017:27017"
    volumes:      
      - "./data/db/mongo:/data:rw"     
    environment:       
      - MONGO_INITDB_ROOT_USERNAME=fiware
      - MONGO_INITDB_ROOT_PASSWORD=fiware
    command: mongod --smallfiles
    networks:
      - fiware     

  sth-comet:
    image: telefonicaiot/fiware-sth-comet:2.2.0
    hostname: sth-comet
    container_name: sth-comet
    volumes:
      - ./config/sth/config.js:/opt/sth/config.js
    links:
      - mongodb-cygnus
    expose:
      - "8666"     
    ports:
      - "8666:8666"
    networks:
      - fiware  