version: "2"

networks:
  fiware:
    external: true

services:
  mongodb:
    image: mongo:3.4.2
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongodb-volume:/data
    command: mongod --smallfiles
    networks:
      - fiware

  orion:
    image: fiware/orion:latest
    hostname: orion
    container_name: orion
    links:
      - mongodb
    expose:
      - "1026"
    ports:
      - "1026:1026"
    command: -dbhost mongodb
    networks:
      - fiware

  cygnus:
    image: fiware/cygnus-ngsi:latest
    hostname: cygnus
    container_name: cygnus
    volumes:
      - "./config/cygnus/agent.conf:/opt/apache-flume/conf/agent.conf:rw"
    links:
      - orion
      - mysql-cygnus
    expose:
      - "5050"
      - "8081"
    ports:
      - "5050:5050"
      - "8081:8081"
    environment:
      - CYGNUS_MYSQL_HOST=mysql-cygnus
      - CYGNUS_MYSQL_PORT=3306
      - CYGNUS_MYSQL_USER=root
      - CYGNUS_MYSQL_PASS=mysql
      - CYGNUS_LOG_LEVEL=INFO
    networks:
      - fiware

  mysql-cygnus:
    image: mysql
    hostname: mysql-cygnus
    container_name: mysql-cygnus
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=YOUR_MYSQL_ROOT_PASSWORD
    volumes:
      - mysql-cygnus-volume:/var/lib/mysql
    networks:
      - fiware

volumes:
  mongodb-volume:
  mysql-cygnus-volume: